version: '3.8'
services:
  db:
    container_name: birt_playground
    image: postgres:14.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5430:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: